### ISSUE TITLE
Standard and Legacy Paths (Using Path parser)

### ISSUE THREAD

**Issue by juanfranblanco** [MelbourneDeveloper/Hardwarewallets.Net#2]
Hi!

For Ethereum we still had the issue for Legacy and Standard paths, so as I mentioned the simplest way was to use @NicolasDorier KeyPath parser, and use the predefined paths for Ethereum. I think the option to include your own path will be good. 

The NBitcoin implementation includes the "hardening" bytes, which is not included in the helper when building indexes.

This is a working sample for Nethereum, most of it could be extracted here.
https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Ledger/LedgerExternalSigner.cs#L150-L162

Also I have extracted from the tests the HidDevice discovery for Windows, I think that would be nice also somewhere in the library with Android.

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco I will look at this tomorrow.

**Comment by MelbourneDeveloper** [comment]
Is this what you mean?

![image](https://user-images.githubusercontent.com/16697547/47316939-0740ef00-d694-11e8-8947-64227f70bdd6.png)

I can see that this example uses "Network.Main" as a parameter for the conversion to string.  None of the hardware wallets take the chain Id as a parameter for getting addresses. They just take an array of unsigned integers.

I'm happy to add more elements to achieve more flexibility. But, there's something missing from my understanding. Perhaps we should have a Skype chat at some point? Maybe I'm just thick?

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco , have you had a chance to look at this?

**Comment by juanfranblanco** [comment]
Sorry I may sound opinionated (much easier when you are not implementing it :) ). My idea was to not leak bip44 for all coins as they might have other needs, scenarios, so keeping a simple interface with just the Path and later on a specialised one with IBIP44Path might be good. But at the moment might be a unnecessary abstraction, so feel free to ignore it.

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco that's exactly what I suggested in https://github.com/MelbourneDeveloper/Hardwarewallets.Net/issues/2#issuecomment-431983994. Is there something I'm not understanding?

**Comment by juanfranblanco** [comment]
Jesus I missed that, "facepalm" "hardslap" so sorry!!! I should read the history again.

**Comment by juanfranblanco** [comment]
You are very welcome to slap me when we meet in person. (I am going to be like a punch bag one of these days)

**Comment by MelbourneDeveloper** [comment]
I think we're on the same page now. Does it work for you?

**Comment by juanfranblanco** [comment]
Yeas of course, that is great.

**Comment by juanfranblanco** [comment]
One further thought, the path will be hardened or unhardened, what it identifies if is hardened might be just one element with ' (if you check the Path of NBitcoin)

**Comment by juanfranblanco** [comment]
https://github.com/MetacoSA/NBitcoin/blob/master/NBitcoin/BIP32/KeyPath.cs#L43-L49

**Comment by MelbourneDeveloper** [comment]
I have to allow for maintaining the information about which elements are hardened and which aren't. That's why there is ToHardened and ToUnhardened. However, this is also possible:

   ```
 public interface IAddressPath
    {
        IList<IAddressPathElement> AddressPathElements { get; }
        uint[] ToArray { get; }
    }

    public interface IAddressPathElement
    {
        uint Value { get; }
        bool IsHardened { get; }
    }
```

The 'IsHardened' property would represent the '

**Comment by MelbourneDeveloper** [comment]
That way if someone wants to unharden the number later, they can use a XOR. But, I need to be able to get the unhardened number.

**Comment by juanfranblanco** [comment]
Ah, awesome !!

**Comment by MelbourneDeveloper** [comment]
Deal. 

Does this code look right for unhardening an element to you? I just need to make sure I can convert both ways.

  ```
  public static class AddressUtilities
    {
        private const uint HardeningConstant = 0x80000000;

        public static uint HardenNumber(uint softNumber)
        {
            return (softNumber | HardeningConstant) >> 0;
        }

        public static uint UnhardenNumber(uint hardNumber)
        {
            return hardNumber ^ HardeningConstant;
        }
    }
```

**Comment by juanfranblanco** [comment]
Looks ok to me (will need to unit test it :) )

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco ok, I can go ahead with these changes, but bear in mind, it's going to be a lot of work to roll these changes through all the libraries. Are you sure that this is for the best?

The changes are:
1. Break the IAddressPath interface in to another interface for BIP44. Then, all references will remain to IAddressPath so it's not necessary to implement the BIP44 properties to use the interface.
2. The IAddressPath interface will have a list of IAddressPathElements that will specify whether a given element is hardened or not (i.e. represent '). This will mean that the path can be converted to and from hardened format, but the ToArray method will just return the indices as they are (hardened or not hardened).

**Comment by juanfranblanco** [comment]
Now I feel bad, but i guess it will work for the best (now better than an even bigger refactoring later).  This way you can derive more paths from a given path, also hardware wallets eventually support any path that is not specific to bip44. Also things like Segwit etc checks won't need to be checked in other coins. The beauty that you keep bip44 is that every element can be interpreted correctly for those needs. Having the capability to actually create your own interface with different meanings per each element in the path will benefit to the end user (regardless).

**Comment by MelbourneDeveloper** [comment]
No worries. You're right . I actually thought about making these changes in the first place. I wish I had made them earlier. I didn't realise that it was going to be something important. I just have to check that it's the right choice because I have to retest lots of stuff.

**Comment by MelbourneDeveloper** [comment]
This is the crux of my solution:

https://github.com/MelbourneDeveloper/Hardwarewallets.Net/blob/Issue%232/src/Hardwarewallets.Net/AddressManagement/AddressPathBase.cs

Check it out in the Issue#2 branch.

**Comment by MelbourneDeveloper** [comment]
I have implemented the change in this branch of Trezor.Net:
https://github.com/MelbourneDeveloper/Trezor.Net/tree/HardwarewalletsUpgrade

It is pointing to a NuGet that you won't have though...

**Comment by MelbourneDeveloper** [comment]
This change has been rolled out to libraries and released as NuGet packages. Just get latest on any of them to receive the change.

Parsing Custom:
`customAddressPath = AddressPathBase.Parse<CustomAddressPath>("m/45/5/3/5'");`

Parsing BIP 44:
`var bip44AddressPath = AddressPathBase.Parse<BIP44AddressPath>("44'/0'/0'/0/0");`

Main Interface:
```
    public interface IAddressPath
    {
        /// <summary>
        /// The collection of IAddressPathElements which make up the address path
        /// </summary>
        List<IAddressPathElement> AddressPathElements { get; }

        /// <summary>
        /// Returns the address path as an array of uints. Indices will be hardended or unhardened depending on their IsHardened property
        /// </summary>
        uint[] ToArray();
    }

    public interface IAddressPathElement
    {
        uint Value { get; }
        bool Harden { get; }
    }

```

@juanfranblanco
