### ISSUE TITLE
myBIP44AddressPath.Change; fails if the change element is set to 1

### ISSUE THREAD

**Issue by Mushroomizer** [MelbourneDeveloper/Hardwarewallets.Net#3]
https://github.com/MelbourneDeveloper/Hardwarewallets.Net/blob/6147e4233156ebdd9c05b60ae428bd5475103f65/src/Hardwarewallets.Net/AddressManagement/BIP44AddressPath.cs#L31

**Comment by Mushroomizer** [comment]
The fix

if (AddressPathElements[3].Value != 0 && AddressPathElements[3].Value != 1) throw new Exception($"{errorPrefix} Change must 0 or 1");

**Comment by MelbourneDeveloper** [comment]
@mushroomizer whoa! That's a big bug. Thanks for pointing it out. Can you please make this change and submit a pull request?

**Comment by Mushroomizer** [comment]
Ive submitted a pull request that fixes it #4

**Comment by Mushroomizer** [comment]
Thanks for Approving!

**Comment by MelbourneDeveloper** [comment]
@mushroomizer thanks for reporting. Unfortunately I don't think I can roll out the NuGet fix for a couple of weeks because I'll be overseas without a laptop.
